git clone https://github.com/derekwyatt/vim-scala.git
git clone https://github.com/kchmck/vim-coffee-script.git
git clone https://github.com/tpope/vim-abolish.git
git clone https://github.com/tpope/vim-bundler.git
git clone https://github.com/tpope/vim-commentary.git
git clone https://github.com/tpope/vim-endwise.git
git clone https://github.com/tpope/vim-eunuch.git
git clone https://github.com/tpope/vim-fugitive.git
git clone https://github.com/tpope/vim-git.git
git clone https://github.com/tpope/vim-haml.git
git clone https://github.com/tpope/vim-markdown.git
git clone https://github.com/tpope/vim-pathogen.git
git clone https://github.com/tpope/vim-ragtag.git
git clone https://github.com/tpope/vim-rails.git
git clone https://github.com/tpope/vim-rake.git
git clone https://github.com/tpope/vim-repeat.git
git clone https://github.com/tpope/vim-rhubarb.git
git clone https://github.com/tpope/vim-rvm.git
git clone https://github.com/tpope/vim-speeddating.git
git clone https://github.com/tpope/vim-surround.git
git clone https://github.com/tpope/vim-unimpaired.git
git clone https://github.com/vim-scripts/The-NERD-Commenter.git
git clone https://github.com/vim-scripts/VimClojure.git
